import Link from "next/link";
import { EVENT_CONFIG } from "@/data/config";
export const metadata = { title: "Privacidad y datos personales · Club de Traders" };
export default function PrivacyPage() {
  return <main className="min-h-screen bg-[#080c14] text-slate-300 px-5 py-12"><article className="max-w-3xl mx-auto space-y-8 leading-relaxed">
    <Link href="/#registro" className="text-cyan-300 underline">Volver al registro</Link>
    <h1 className="text-3xl font-bold text-white">Privacidad y datos personales</h1>
    <p>Información del formulario del Bootcamp · Versión del 17 de septiembre de 2026.</p>
    <section className="space-y-3"><h2 className="text-xl font-bold text-white">Quién organiza y atiende tus solicitudes</h2><p>Richard Veintimilla, organizador de Club de Traders, es el contacto responsable de la inscripción y las comunicaciones del Bootcamp. Escribe a <a className="text-cyan-300 underline" href={`mailto:${EVENT_CONFIG.academia.email}`}>{EVENT_CONFIG.academia.email}</a> o al WhatsApp {EVENT_CONFIG.whatsappDisplay}.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-bold text-white">Datos y finalidad del registro</h2><p>Pedimos nombre, correo y teléfono para gestionar tu participación y las comunicaciones de este Bootcamp. Guardamos también la fecha, un identificador de inscripción, tu autorización y la versión de este aviso. La base del registro y sus comunicaciones es tu consentimiento, que prestas al marcar la casilla y enviar el formulario. Los campos son necesarios para completar este formulario; sin la autorización de registro no se envían. Si el correo o el teléfono son incorrectos, es posible que no podamos identificar tu inscripción o hacerte llegar las comunicaciones.</p><p>Este registro no abre cuentas de inversión ni autoriza publicidad de otros eventos. No se toman decisiones automatizadas sobre tu perfil financiero.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-bold text-white">Medición opcional</h2><p>Solo si marcas la casilla opcional asociamos a tu inscripción las etiquetas de campaña presentes en el enlace (fuente, medio, campaña, contenido y término) y la fecha de tu primer clic en el botón de WhatsApp después del registro. Puedes inscribirte sin aceptar esta medición.</p><p>Esta información está vinculada a tu registro: no es anónima. Mide el clic, no acredita que hayas enviado un mensaje o entrado en un grupo. No instalamos cookies de publicidad ni píxeles de seguimiento para esta medición.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-bold text-white">Dónde se procesan y quién puede acceder</h2><p>La web utiliza Vercel para recibir el formulario y Google Apps Script y Google Sheets para guardarlo en una hoja privada. La cuenta técnica que mantiene la integración pertenece actualmente a Ángel, administrador de la web, y no se ha completado todavía su transferencia al organizador. Quienes administran esas cuentas pueden acceder a la información para operar el servicio.</p><p>Estos proveedores pueden procesar datos fuera de Ecuador conforme a sus condiciones. La hoja no es pública. El alojamiento también procesa información técnica de las solicitudes. Para frenar abusos usamos temporalmente un identificador derivado de la dirección de conexión; no se añade a la hoja de inscritos. Los registros técnicos de la aplicación incluyen duración, resultado y un identificador de solicitud, sin el contenido del formulario.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-bold text-white">Al continuar a WhatsApp</h2><p>Se abre un servicio externo de WhatsApp/Meta con un mensaje preparado que incluye tu nombre. Puedes editarlo y debes enviarlo tú para contactar con Richard. No incluimos tu correo ni tu teléfono en ese enlace. WhatsApp aplica sus propias condiciones; si decides entrar en un grupo, sus participantes pueden ver tu número según la configuración del servicio.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-bold text-white">Conservación y control de tus datos</h2><p>Actualmente la integración no aplica un borrado automático ni tiene un plazo de conservación definitivo configurado. Los registros permanecen en la hoja hasta su eliminación por el administrador. Puedes solicitar su eliminación o retirar tus autorizaciones mediante el contacto indicado arriba.</p><p>Puedes solicitar acceso, rectificación y actualización, eliminación, oposición, suspensión o limitación del tratamiento y, cuando proceda, la portabilidad de tus datos. Puedes retirar por separado el consentimiento para comunicaciones o medición. Para ejercer estos derechos o presentar una reclamación, utiliza el correo o WhatsApp del organizador indicados arriba y señala el correo utilizado en el registro y tu solicitud. Para portabilidad, puedes solicitar una copia en formato estructurado y legible por máquina o su transmisión cuando corresponda. Puede ser necesario verificar tu identidad de forma proporcionada; no envíes documentos de identidad sin que se te soliciten y se indique un canal adecuado. Retirar el consentimiento no afecta al tratamiento ya realizado. También puedes acudir a la <a href="https://spdp.gob.ec/" className="text-cyan-300 underline" target="_blank" rel="noopener noreferrer">Superintendencia de Protección de Datos Personales de Ecuador</a>.</p></section>
  </article></main>;
}
